Create car - CRUD
TimmyChan99/Car-rental-app-back-end pull request #18
Opened 2022-06-09 16:09 UTC by yaseerokino

### Reservation Backend API

**Hey Team**

_**In this milestone PR, I completed the following:**_

- Created the endpoint for PATCH, GET, DELETE and POST requests for cars r
- Update the User schema with a role column 
- Created method to allow only admin user create, update and delete a car

2022-06-09 20:28 UTC, TimmyChan99 requested changes
**Required Changes ♻️**
Hi @yaseerokino 

Good job so far!
There are some issues that you still need to work on to go to the next task but you are almost there!

<img src="https://media4.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif"/>

2022-06-09 20:28 UTC, TimmyChan99 commented on app/controllers/api/v1/cars_controller.rb
> +  end
Good job there, please make sure to permit also the `reserved` parameter to allow the user to update the car status if it is reserved or not.

2022-06-09 20:31 UTC, yaseerokino commented
Hey @TimmyChan99 the reserved field should be updated automatically when the user reserves a car.

2022-06-09 20:44 UTC, TimmyChan99 approved these changes
**Status: Approved** 🟢
 
Hey @yaseerokino,

If the status already updated automatically then your project is complete you are ready to merge it   👍

2022-06-12 19:36 UTC, Mwapsam approved these changes

2022-06-13 05:08 UTC, merged